ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM dba_users WHERE username = 'DEV_USER';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER DEV_USER IDENTIFIED BY "9l6s7sIKR#3oED2B"';
    EXECUTE IMMEDIATE 'ALTER USER DEV_USER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO DEV_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO DEV_USER';
  END IF;
END;
/